version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: garin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    volumes:
      - ~/docker-volumes/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
