# Generated by Django 5.1.6 on 2025-02-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_consumer_is_admin_and_more'),
        ('authtoken', '0004_alter_tokenproxy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerToken',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authtoken.token',),
        ),
    ]
