# Generated by Django 5.1.6 on 2025-02-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_consumertoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsumerToken',
        ),
    ]
