# Generated by Django 5.1.6 on 2025-03-07 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_consumertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwareproduct',
            name='genres',
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.genre'),
            preserve_default=False,
        ),
    ]
