# Generated by Django 5.1.6 on 2025-03-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_softwareproduct_genres_softwareproduct_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareproduct',
            name='image',
            field=models.TextField(),
        ),
    ]
