# Generated by Django 5.1.6 on 2025-03-10 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_softwareproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
